on:
  workflow_call:
    inputs:
      channel:
        required: false
        type: string
        default: 'stable'
      run_ios:
        required: false
        type: boolean
        default: false
      run_android_build:
        required: false
        type: boolean
        default: false
      run_codecov:
        required: false
        type: boolean
        default: false
      upload_apk:
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        required: false


jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.channel }}

      - name: Flutter --version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Format check
        run: flutter format --set-exit-if-changed .

      - name: Static analysis
        run: flutter analyze

      - name: Run unit tests (with coverage)
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        if: ${{ inputs.run_codecov && secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  android-build:
    if: ${{ inputs.run_android_build }}
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.channel }}

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        if: ${{ inputs.upload_apk }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/*.apk

  ios-build:
    if: ${{ inputs.run_ios }}
    runs-on: macos-latest
    needs: analyze-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.channel }}

      - name: Get dependencies
        run: flutter pub get

      - name: Attempt iOS build (no codesign)
        run: |
          # Nota: para archivar y subir a App Store / device necesitas firmar (certs, provisioning)
          # Este paso intenta una build básica sin firmar.
          flutter build ios --no-codesign || true

      - name: Upload iOS build logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: build/** || .